"""Project-wide paths and constants.

All paths resolve from the project root, which is 2 levels above this file
(src/bimkg/config.py -> src/bimkg -> src -> project root).

Directory layout follows the Medallion architecture (Bronze/Silver/Gold/
Ontology) to align with Palantir Foundry dataset organization:

    data/raw/         Bronze — untouched source (authoritative snapshot)
    data/clean/       Silver — typed, validated, normalized per-table
    data/enriched/    Gold   — joined, flagged, SI-unitized, with lineage
    data/ontology/    Object Type / Link Type / OWL outputs for Foundry
    data/powerbi/     PowerBI star schema (regenerated by Phase 1d)
    data/backup/      Frozen legacy artifacts (do not modify)
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Project root
# ---------------------------------------------------------------------------

PROJECT_ROOT: Path = Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------------------
# Snapshot identifier (single authoritative snapshot)
# ---------------------------------------------------------------------------

SNAPSHOT: str = "2026-04-07"

# ---------------------------------------------------------------------------
# Data layer roots (Medallion architecture)
# ---------------------------------------------------------------------------

DATA_ROOT: Path = PROJECT_ROOT / "data"

DATA_RAW_ROOT: Path = DATA_ROOT / "raw"           # Bronze
DATA_CLEAN_ROOT: Path = DATA_ROOT / "clean"       # Silver
DATA_ENRICHED_ROOT: Path = DATA_ROOT / "enriched" # Gold
DATA_ONTOLOGY_ROOT: Path = DATA_ROOT / "ontology" # Ontology-ready
DATA_POWERBI_ROOT: Path = DATA_ROOT / "powerbi"   # PowerBI star schema
DATA_BACKUP_ROOT: Path = DATA_ROOT / "backup"     # Frozen legacy

# ---------------------------------------------------------------------------
# Snapshot-specific directories
# ---------------------------------------------------------------------------

DATA_RAW: Path = DATA_RAW_ROOT / "dxtnavis" / SNAPSHOT
DATA_CLEAN: Path = DATA_CLEAN_ROOT / SNAPSHOT
DATA_ENRICHED: Path = DATA_ENRICHED_ROOT / SNAPSHOT
DATA_ONTOLOGY: Path = DATA_ONTOLOGY_ROOT / SNAPSHOT
POWERBI_DIR: Path = DATA_POWERBI_ROOT / SNAPSHOT

# ---------------------------------------------------------------------------
# Bronze — raw source files (read-only, authoritative)
# ---------------------------------------------------------------------------

RAW_ALL_PROPERTIES: Path = DATA_RAW / "AllProperties_20260407_184650.csv"
RAW_REFINING_XLSX: Path = DATA_RAW / "Refining_ObjectID_20260407_192047.xlsx"
RAW_ADJACENCY: Path = DATA_RAW / "adjacency.csv"
RAW_GEOMETRY: Path = DATA_RAW / "geometry.csv"
RAW_VALIDATION: Path = DATA_RAW / "validation.csv"
RAW_CONNECTED_GROUPS: Path = DATA_RAW / "connected_groups.csv"
RAW_TESSELLATION_FAILURES: Path = DATA_RAW / "tessellation_failures.csv"
RAW_MANIFEST: Path = DATA_RAW / "manifest.json"

# ---------------------------------------------------------------------------
# Silver — Phase 1a clean parquet outputs
# ---------------------------------------------------------------------------

CLEAN_OBJECTS: Path = DATA_CLEAN / "bim_objects.parquet"
CLEAN_ADJACENCY: Path = DATA_CLEAN / "bim_adjacency.parquet"
CLEAN_HIERARCHY: Path = DATA_CLEAN / "bim_hierarchy.parquet"
CLEAN_CONNECTED_GROUPS: Path = DATA_CLEAN / "bim_connected_groups.parquet"

# ---------------------------------------------------------------------------
# Gold — Phase 1a enriched outputs with flags, SI units, lineage
# ---------------------------------------------------------------------------

ENRICHED_OBJECTS: Path = DATA_ENRICHED / "bim_objects_enriched.parquet"
ENRICHED_ADJACENCY_SYM: Path = DATA_ENRICHED / "bim_adjacency_sym.parquet"
SQLITE_BIMKG: Path = DATA_ENRICHED / "bimkg.db"

# ---------------------------------------------------------------------------
# Ontology — Phase 1d + Phase 2 outputs (Foundry-ready)
# ---------------------------------------------------------------------------

ONTOLOGY_OBJECT_TYPES: Path = DATA_ONTOLOGY / "object_types"
ONTOLOGY_LINK_TYPES: Path = DATA_ONTOLOGY / "link_types"
ONTOLOGY_OWL_DIR: Path = DATA_ONTOLOGY / "owl"

ONTOLOGY_OWL: Path = ONTOLOGY_OWL_DIR / "bim-ontology.owl"
ONTOLOGY_INSTANCES: Path = ONTOLOGY_OWL_DIR / "bim-instances.ttl"
ONTOLOGY_SHAPES: Path = ONTOLOGY_OWL_DIR / "bim-shapes.ttl"
ONTOLOGY_INFERRED: Path = ONTOLOGY_OWL_DIR / "bim-inferred.ttl"

# ---------------------------------------------------------------------------
# Backup — frozen legacy C# backend outputs (read-only reference)
# ---------------------------------------------------------------------------

BACKUP_CSHARP: Path = DATA_BACKUP_ROOT / "dxtnavis-csharp-20260411"
LEGACY_SQLITE: Path = BACKUP_CSHARP / "working" / "dxtnavis" / "dxtnavis-semantic.db"
LEGACY_POWERBI: Path = BACKUP_CSHARP / "powerbi" / SNAPSHOT

# ---------------------------------------------------------------------------
# Deprecated alias — kept for backward compatibility with conftest.py fixtures
# that reference SQLITE_DB. Points to the legacy location after reorganization.
# New code should use SQLITE_BIMKG or LEGACY_SQLITE explicitly.
# ---------------------------------------------------------------------------

SQLITE_DB: Path = LEGACY_SQLITE

# ---------------------------------------------------------------------------
# Expected counts from the 2026-04-07 snapshot (used in tests)
# ---------------------------------------------------------------------------

EXPECTED_OBJECT_COUNT: int = 12009
EXPECTED_ADJACENCY_COUNT: int = 110173
EXPECTED_CONNECTED_GROUPS: int = 3355
EXPECTED_GIANT_GROUP_SIZE: int = 8626
EXPECTED_PIPELINE_COUNT: int = 157
